services:
  postgres-db:
    image: pgvector/pgvector:pg16
    container_name: my_postgres
    environment:
      POSTGRES_USER: xxx
      POSTGRES_PASSWORD: yyy
      POSTGRES_DB: zzz
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always
