FROM golang:1.24-alpine

RUN apk update && apk add --no-cache git

WORKDIR /app

ENV GOFLAGS="-buildvcs=false"

RUN go install github.com/air-verse/air@v1.61.7

COPY go.mod go.sum* ./
RUN go mod download

COPY . .

CMD ["air", "-c", ".air.toml"]
